# Generated by Django 4.2.5 on 2023-11-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios_Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateField(null=True)),
                ('resenha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.resenha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='resenha',
            name='comentarios',
            field=models.ManyToManyField(related_name='comentario_resenha', to='livro.comentarios_resenha'),
        ),
    ]
