# Generated by Django 4.2.5 on 2023-09-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livros',
            table='livro',
        ),
    ]
