# Generated by Django 4.2.5 on 2023-10-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_confirmado_usuario_data_expiracao_token_and_more'),
        ('livro', '0002_alter_livros_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('texto', models.TextField()),
                ('avaliacao', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livros')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
