# Generated by Django 4.2.5 on 2023-10-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_confirmado_usuario_data_expiracao_token_and_more'),
        ('livro', '0004_livros_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lista', models.CharField(max_length=100)),
                ('livros', models.ManyToManyField(related_name='livros_salvos', to='livro.livros')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
