# Generated by Django 4.2.5 on 2023-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('token_confirmacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_expiracao_token', models.DateTimeField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
